tastybento/askyblock

- config.yml
- plugin.yml
- src/com/wasteofplastic/askyblock/ASkyBlock.java
- src/com/wasteofplastic/askyblock/IslandGuard.java
- src/com/wasteofplastic/askyblock/Settings.java
Tested and fixed bugs with island guard.
Added options to allow block place and break at spawn.
> Fixed expel bug.

- config.yml
- src/com/wasteofplastic/askyblock/Settings.java
- src/com/wasteofplastic/askyblock/commands/IslandCmd.java
Hi Tastybento,
When a player has permissions for multiple islands, the first island is always chosen, and then created.
I think it is better to choose an island randomly from the resulting list. I needed this feature for my server, and maybe it will be useful for others.
Thanks,
Lorgan
> Select island randomly

- src/com/wasteofplastic/askyblock/TopTen.java
Add exclude from topten feature for mod who has
acidisland.mod.excludetopten
> Add Exclude from Topten for Mod

- src/com/wasteofplastic/askyblock/commands/IslandCmd.java
> Use max team.maxsize permissions in /is team

- src/com/wasteofplastic/askyblock/ASkyBlock.java
- src/com/wasteofplastic/askyblock/events/IslandDeleteEvent.java
Add an event that is called when an island is deleted.
> Add IslandDeleteEvent

- README.md
> Add issue time and percentage

- config.yml
- locale/en-US.yml
- locale/es-ES.yml
- locale/locale.yml
- plugin.yml
- src/com/wasteofplastic/askyblock/ASLocale.java
- src/com/wasteofplastic/askyblock/ASkyBlock.java
- src/com/wasteofplastic/askyblock/ASkyBlockAPI.java
- src/com/wasteofplastic/askyblock/Island.java
- src/com/wasteofplastic/askyblock/Settings.java
- src/com/wasteofplastic/askyblock/listeners/PlayerEvents.java
- src/com/wasteofplastic/askyblock/panels/SettingsPanel.java
> Add a flag controlling chorus fruit use

- locale/nl-NL.yml
thanks to @jack-mckalling for pointing these out
> fix some bad translation faults

- src/com/wasteofplastic/askyblock/commands/IslandCmd.java
i created /is tc because /is teamchat is to long to type in some cases
> added /is tc

- src/com/wasteofplastic/askyblock/panels/BiomeItem.java
- src/com/wasteofplastic/askyblock/panels/CPItem.java
- src/com/wasteofplastic/askyblock/panels/IPItem.java
- src/com/wasteofplastic/askyblock/panels/SPItem.java
- src/com/wasteofplastic/askyblock/panels/WarpPanel.java
Just added a ChatColor.WHITE before panel items' display names to make
them looking better
> Better items names

- config.yml
- plugin.yml
- src/com/wasteofplastic/askyblock/ASLocale.java
- src/com/wasteofplastic/askyblock/ASkyBlock.java
- src/com/wasteofplastic/askyblock/Island.java
- src/com/wasteofplastic/askyblock/Settings.java
- src/com/wasteofplastic/askyblock/listeners/IslandGuard.java
- src/com/wasteofplastic/askyblock/panels/SettingsPanel.java
Idea got from : https://github.com/tastybento/askyblock/issues/212
> Setting to toggle join/leave is. messages

- config.yml
- src/com/wasteofplastic/askyblock/ASLocale.java
- src/com/wasteofplastic/askyblock/ASkyBlock.java
- src/com/wasteofplastic/askyblock/Settings.java
- src/com/wasteofplastic/askyblock/TopTen.java
Idea got from : https://github.com/tastybento/askyblock/issues/104
+ Added a config option "islandtopteninchat" to give the ability to use the old chat top ten
> Added a GUI for Top 10 Islands

- config.yml
- src/com/wasteofplastic/askyblock/ASLocale.java
- src/com/wasteofplastic/askyblock/ASkyBlock.java
- src/com/wasteofplastic/askyblock/Settings.java
- src/com/wasteofplastic/askyblock/commands/IslandCmd.java
- src/com/wasteofplastic/askyblock/listeners/LavaCheck.java
Ready to merge. I had not the time to add as much things i originally wanted to. 
Just a few fixes and improvements : 
- #346 : Use /minecraft:title instead of /title to prevent issues with overrides
- #352 : MagicCobbleGenerator won't lead to numerous Random objects
- #282 : Added a config option for **useMinishop** and a message in the locale if it is disabled
> Fixes and improvements [READY]

- locale/en-GB.yml
- locale/en-US.yml
- locale/fr-FR.yml
- locale/locale.yml
Updated en_us, en_gb, fr_fr and locale with error.minishopDisabled and warps.errorNotEnoughLevel.
> Locales update

- config.yml
- src/com/wasteofplastic/askyblock/ASkyBlock.java
- src/com/wasteofplastic/askyblock/Settings.java
- src/com/wasteofplastic/askyblock/listeners/IslandGuard.java
https://github.com/tastybento/askyblock/issues/309
> Toggle offline redstone

- src/com/wasteofplastic/askyblock/listeners/IslandGuard1_9.java
Closes #403
not Tested got not all the jars
> Added cleanup of ASkyBlockNP Team when player Leaves server

- src/com/wasteofplastic/askyblock/TopTen.java
https://github.com/tastybento/askyblock/issues/414
> Added a teleport to warp when click on head

- config.yml
- src/com/wasteofplastic/askyblock/listeners/NetherPortals.java
https://github.com/tastybento/askyblock/issues/188
> Nethertrees without island-style nether

- locale/locale.yml
- src/com/wasteofplastic/askyblock/ASLocale.java
- src/com/wasteofplastic/askyblock/LevelCalc.java
- src/com/wasteofplastic/askyblock/LevelCalcByChunk.java
https://github.com/tastybento/askyblock/issues/208
> Points required to reach next level

- config.yml
- src/com/wasteofplastic/askyblock/ASkyBlock.java
- src/com/wasteofplastic/askyblock/Settings.java
- src/com/wasteofplastic/askyblock/listeners/PlayerEvents.java
https://github.com/tastybento/askyblock/issues/380
Functional, but may need some fixes for indentation.
> Give Permissions when on island

- src/com/wasteofplastic/askyblock/commands/AdminCmd.java
Some plugins missing a slash in the message sent.
Reference to issue #574
> Update Admin helpMessages output

- plugin.yml
- src/com/wasteofplastic/askyblock/listeners/PlayerEvents.java
Addresses https://github.com/tastybento/askyblock/issues/548
> Added permission to bypass blocked commands and blocked teleportation while falling

- config.yml
- src/com/wasteofplastic/askyblock/PluginConfig.java
- src/com/wasteofplastic/askyblock/Settings.java
- src/com/wasteofplastic/askyblock/commands/IslandCmd.java
- src/com/wasteofplastic/askyblock/schematics/Schematic.java
* Cleaned up & updated comments in the schematic section in config
* Added an optional companion spawn-block (related to https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/1)
* Add startcommands for schematics (related to https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/69)
> Schematics

- config.yml
- plugin.yml
- src/com/wasteofplastic/askyblock/Island.java
- src/com/wasteofplastic/askyblock/listeners/IslandGuard.java
- src/com/wasteofplastic/askyblock/panels/SettingsPanel.java
* FISHING_ROD related to
https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/29
* SPLASH_POTION related to
https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/66
> Added FISHING_ROD & SPLASH_POTION in Island Guard Settings

- src/com/wasteofplastic/askyblock/LevelCalcByChunk.java
Fixes https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/86
> getPointsToNextLevel() was sometimes returning 0

- src/com/wasteofplastic/askyblock/LevelCalcByChunk.java
- src/com/wasteofplastic/askyblock/events/IslandLevelEvent.java
- src/com/wasteofplastic/askyblock/events/IslandPostLevelEvent.java
- src/com/wasteofplastic/askyblock/events/IslandPreLevelEvent.java
* Depreciated IslandLevelEvent
* Added IslandPostLevelEvent
* Adjusted code
Related to
https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/87
> Splited player notif from IslandPreLevelEvent

- locale/en-GB.yml
- locale/en-US.yml
- locale/fr-FR.yml
- src/com/wasteofplastic/askyblock/ASLocale.java
- src/com/wasteofplastic/askyblock/commands/IslandCmd.java
And added plugin name & version in /is about
Related to https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/81
> Made /is help header editable

- src/com/wasteofplastic/askyblock/TopTen.java
As I thought that the default appearance of the text of the top ten heads was a little bland, I decided to change it a bit to make it a little more appealing. Just my suggestion, in no way do you have to accept this change.
If possible though, could you compile a version of the plugin with just this class edited for me? Would be much appreciated :)
> Changed default text of top ten GUI

- config.yml
Related to https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/80
> Added OCEAN and SKY biomes to config

- src/com/wasteofplastic/askyblock/events/IslandPostLevelEvent.java
Addresses
https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/107
> Add setters to fake values in IslandPostLevelEvent

- config.yml
- src/com/wasteofplastic/askyblock/PluginConfig.java
- src/com/wasteofplastic/askyblock/Settings.java
- src/com/wasteofplastic/askyblock/commands/IslandCmd.java
- src/com/wasteofplastic/askyblock/listeners/ChatListener.java
Adresses
https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/27
I did my best, but I'm not sure I didn't make mistakes. The way TeamChat is handled is a bit messy, so I had to knock up the coop-including.
> Added option to include coop players in teamchat

- locale/pl-PL.yml
https://www.spigotmc.org/threads/askyblock.30325/page-190#post-2369040
> Fixed welcomeLine misspelling in PL locale

- plugin.yml
- src/com/wasteofplastic/askyblock/panels/SettingsPanel.java
Addresses https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/92
> Added asb.settings.* node to asb.admin.*

- config.yml
- src/com/wasteofplastic/askyblock/ASkyBlock.java
- src/com/wasteofplastic/askyblock/PluginConfig.java
- src/com/wasteofplastic/askyblock/Settings.java
- src/com/wasteofplastic/askyblock/commands/IslandCmd.java
- src/com/wasteofplastic/askyblock/util/ASBParser.java
and started the ASBParser class that will be used to parse sounds & items for the panels and the challenges.
Adresses https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/30
> Added option to customize warp sound

- config.yml
- src/com/wasteofplastic/askyblock/PluginConfig.java
- src/com/wasteofplastic/askyblock/Settings.java
- src/com/wasteofplastic/askyblock/commands/IslandCmd.java
Addresses https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/37
> Added option to allow use minishop in every worlds

- src/com/wasteofplastic/askyblock/listeners/IslandGuard.java
Player could eat cake on other players islands : it was giving food but wasn't consuming the cake
> Fixes https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/128

- config.yml
- locale/en-GB.yml
- locale/en-US.yml
- locale/fr-FR.yml
- src/com/wasteofplastic/askyblock/ASLocale.java
- src/com/wasteofplastic/askyblock/Island.java
- src/com/wasteofplastic/askyblock/listeners/IslandGuard.java
- src/com/wasteofplastic/askyblock/panels/SettingsPanel.java
Adresses https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/132
And did a little cleanup with the comments. Some were not corresponding to the flag they were explaining.
> Added HURT_VILLAGERS settingflag

- src/com/wasteofplastic/askyblock/commands/IslandCmd.java
> Added alternative arguments for /is go

- config.yml
- src/com/wasteofplastic/askyblock/ASkyBlockAPI.java
- src/com/wasteofplastic/askyblock/CoopPlay.java
- src/com/wasteofplastic/askyblock/LevelCalcByChunk.java
- src/com/wasteofplastic/askyblock/Messages.java
- src/com/wasteofplastic/askyblock/PluginConfig.java
- src/com/wasteofplastic/askyblock/Settings.java
- src/com/wasteofplastic/askyblock/WarpSigns.java
- src/com/wasteofplastic/askyblock/commands/AdminCmd.java
- src/com/wasteofplastic/askyblock/commands/Challenges.java
- src/com/wasteofplastic/askyblock/commands/IslandCmd.java
- src/com/wasteofplastic/askyblock/listeners/JoinLeaveEvents.java
- src/com/wasteofplastic/askyblock/listeners/PlayerEvents.java
Related to https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/148
Added a list in config to choose what type of history message have to be sent.
> History offline messages

- config.yml
- src/com/wasteofplastic/askyblock/ASkyBlock.java
- src/com/wasteofplastic/askyblock/PlayerCache.java
- src/com/wasteofplastic/askyblock/PluginConfig.java
- src/com/wasteofplastic/askyblock/Settings.java
- src/com/wasteofplastic/askyblock/commands/AdminCmd.java
- src/com/wasteofplastic/askyblock/commands/IslandCmd.java
- src/com/wasteofplastic/askyblock/util/Util.java
Related to https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/130
> Delete user files on purge

- locale/en-GB.yml
- locale/en-US.yml
- locale/fr-FR.yml
- src/com/wasteofplastic/askyblock/ASLocale.java
- src/com/wasteofplastic/askyblock/commands/IslandCmd.java
Related to https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/158
> Added confirmation to /is kick

- src/com/wasteofplastic/askyblock/ASkyBlock.java
- src/com/wasteofplastic/askyblock/PluginConfig.java
Was disabling the plugin without creating config.new.yml
> Fixed uptodate config checker

- config.yml
- locale/en-GB.yml
- locale/en-US.yml
- locale/fr-FR.yml
- plugin.yml
- src/com/wasteofplastic/askyblock/ASLocale.java
- src/com/wasteofplastic/askyblock/Island.java
- src/com/wasteofplastic/askyblock/listeners/IslandGuard.java
- src/com/wasteofplastic/askyblock/panels/SettingsPanel.java
Related to https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/94
> Added INTERACT_TAMED setting

- locale/cs-CS.yml
- locale/de-DE.yml
- locale/en-GB.yml
- locale/en-US.yml
- locale/es-ES.yml
- locale/fi-FI.yml
- locale/fr-FR.yml
- locale/it-IT.yml
- locale/jp-JP.yml
- locale/ko-KR.yml
- locale/nl-NL.yml
- locale/pl-PL.yml
- locale/pt-BR.yml
- locale/ru-RU.yml
- locale/sk-SK.yml
- locale/vi-VN.yml
- locale/zh-CN.yml
- locale/zh-TW.yml
- src/com/wasteofplastic/askyblock/ASLocale.java
- src/com/wasteofplastic/askyblock/ASkyBlock.java
- src/com/wasteofplastic/askyblock/NotSetup.java
- src/com/wasteofplastic/askyblock/util/Util.java
And edited Util.sendMessage() in order to split messages using \n
> Added NotSetup reason for outdated config. Localized NotSetup messages.

- src/com/wasteofplastic/askyblock/AcidTask.java
- src/com/wasteofplastic/askyblock/events/acid/EntityDamageByAcidEvent.java
- src/com/wasteofplastic/askyblock/events/acid/ItemDestroyByAcidEvent.java
- src/com/wasteofplastic/askyblock/events/acid/ItemFillWithAcidEvent.java
- src/com/wasteofplastic/askyblock/events/acid/PlayerDamageByAcidEvent.java
- src/com/wasteofplastic/askyblock/events/acid/PlayerDrinkAcidEvent.java
- src/com/wasteofplastic/askyblock/listeners/AcidEffect.java
- src/com/wasteofplastic/askyblock/listeners/AcidInventory.java
Related https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/175
- EntityDamageByAcidEvent
- PlayerDamageByAcidEvent
- ItemDestroyByAcidEvent
- PlayerDrinkAcidEvent
- ItemFillWithAcidEvent
> Added new events related to acid

- src/com/wasteofplastic/askyblock/Island.java
- src/com/wasteofplastic/askyblock/PluginConfig.java
- src/com/wasteofplastic/askyblock/SafeSpotTeleport.java
Fixes tastybento/ASkyBlock-Bugs-N-Features#178
Fixes tastybento/ASkyBlock-Bugs-N-Features#184
Fixes tastybento/ASkyBlock-Bugs-N-Features#183
Fixes tastybento/ASkyBlock-Bugs-N-Features#170
> Merged 3.0.6.5 bug fixes

- config.yml
- locale/en-GB.yml
- locale/en-US.yml
- locale/fr-FR.yml
- plugin.yml
- src/com/wasteofplastic/askyblock/ASLocale.java
- src/com/wasteofplastic/askyblock/PluginConfig.java
- src/com/wasteofplastic/askyblock/Settings.java
- src/com/wasteofplastic/askyblock/listeners/AcidEffect.java
- src/com/wasteofplastic/askyblock/listeners/PlayerEvents.java
Related to https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/33
> Not allow /is when in acid

- config.yml
Related to https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/153
> Made LEVER_BUTTON editable in Settings GUI

- plugin.yml
- src/com/wasteofplastic/askyblock/commands/IslandCmd.java
Related to https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/190
> Added "island.name.format" permission to color/format island name

- config.yml
- plugin.yml
- src/com/wasteofplastic/askyblock/ASLocale.java
- src/com/wasteofplastic/askyblock/Island.java
- src/com/wasteofplastic/askyblock/PluginConfig.java
- src/com/wasteofplastic/askyblock/Settings.java
- src/com/wasteofplastic/askyblock/listeners/IslandGuard.java
- src/com/wasteofplastic/askyblock/listeners/IslandGuard1_9.java
- src/com/wasteofplastic/askyblock/panels/SettingsPanel.java
Related to https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/186
Also removed unused allowfireextinguish setting.
> Moved CREEPER_DAMAGE and TNT_DAMAGE to island settings

- src/com/wasteofplastic/askyblock/commands/AdminCmd.java
it was doing the opposite of what it should do
> Fixed purge prevention

- config.yml
- plugin.yml
- src/com/wasteofplastic/askyblock/PluginConfig.java
- src/com/wasteofplastic/askyblock/Settings.java
- src/com/wasteofplastic/askyblock/commands/IslandCmd.java
Related to https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/71
> Added commands run when being promoted as leader (or demoted)

- locale/zh-CN.yml
> Massive Chinese l10n

- config.yml
- src/com/wasteofplastic/askyblock/ASkyBlock.java
- src/com/wasteofplastic/askyblock/PluginConfig.java
- src/com/wasteofplastic/askyblock/Settings.java
Related to https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/289
> Added option to toggle command feedback silencing

- src/com/wasteofplastic/askyblock/listeners/IslandGuard.java
Fixes https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/373
The server owner who sent me this issue asks for a quick patch. Maybe can you build a pre-release?
> Fixes NPE when placing a spawner with a null lore

- locale/en-GB.yml
- locale/en-US.yml
- locale/fr-FR.yml
- src/com/wasteofplastic/askyblock/ASLocale.java
- src/com/wasteofplastic/askyblock/commands/AdminCmd.java
Related to https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/234
> Provide an estimated run time before launching purge

- config.yml
- src/com/wasteofplastic/askyblock/PluginConfig.java
- src/com/wasteofplastic/askyblock/Settings.java
- src/com/wasteofplastic/askyblock/listeners/IslandGuard.java
I just changed allowAutoActivator to allowedFakePlayers. We'll need some feedback to know what events we should also listen.
Related to https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/402
> Changed allowAutoActivator to a more generic option to allow compatibilty with more mods

- locale/en-GB.yml
- locale/en-US.yml
- locale/fr-FR.yml
- src/com/wasteofplastic/askyblock/ASLocale.java
- src/com/wasteofplastic/askyblock/commands/IslandCmd.java
Related to https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/81
> Made /is help header customisable (pushed again for 3.0.6.12)

- src/com/wasteofplastic/askyblock/commands/Challenges.java
Fixes https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/488
This may break some challenges though. because it will require the exact materialdata (with the same material and data), but that might only be some minor edge cases.
> "island" challenges now take care of the data of the block

- src/com/wasteofplastic/askyblock/listeners/ChatListener.java
Fixes https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/678
Works fine for me, but more testing might be needed, as I'm not a big user of "BigInteger"
> Islands over 1M levels should now display fancier

- config.yml
- src/com/wasteofplastic/askyblock/PluginConfig.java
- src/com/wasteofplastic/askyblock/Settings.java
- src/com/wasteofplastic/askyblock/WarpSigns.java
- src/com/wasteofplastic/askyblock/commands/IslandCmd.java
It solves this: https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/698
> Option To Create Warps For Coops and fix a Typo.

- src/com/wasteofplastic/askyblock/commands/IslandCmd.java
Supports both existing functionality and new functionality of /is value <MATERIALNAME>
Allows lookup of a material without having it in your hand.
> Add functionality to /is value for passing in a material name.

- src/com/wasteofplastic/askyblock/ASkyBlockAPI.java
In my previous PR I must have missed that somehow but it worked when I tested it, I must have made an error while copying it to the PR branch... Sorry about that :/
> Actually return the new island

- src/com/wasteofplastic/askyblock/listeners/PlayerEvents.java
Invincible visitors wasn't working because of some mistake caused by code cleanup. Fixed that.
> Fixed invincible visitors
